# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchitem',
            name='IP_location',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
    ]
