# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180711_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('-digit_value',), 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AddField(
            model_name='feature',
            name='digit_value',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
