# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180711_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='digit_value',
            field=models.BooleanField(editable=False),
        ),
    ]
