# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180711_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=30, null=True, verbose_name='англ_назва'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_digit',
            field=models.BooleanField(default=False, verbose_name='Числова х-ка'),
        ),
    ]
