# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shop.models.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20180711_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Значення')),
                ('unit', models.CharField(blank=True, max_length=5, null=True, verbose_name='Од. виміру')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Feature', verbose_name='Назва')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Розмір товару',
                'verbose_name_plural': 'Розміри товару',
            },
        ),
        migrations.AlterField(
            model_name='catalog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.model_utils.update_filename, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=shop.models.model_utils.update_filename, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.model_utils.update_filename, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.model_utils.update_filename, verbose_name='Фото'),
        ),
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together=set([('feature', 'product')]),
        ),
    ]
