# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-23 18:22
from __future__ import unicode_literals

from django.db import migrations
# from shop.models.product import Dimension, ProductFeature


def move_dimensions_from_product_features(apps, schema_editor):
    Dimension = apps.get_model('shop', 'Dimension')
    ProductFeature = apps.get_model('shop', 'ProductFeature')
    productfeatures = ProductFeature.objects.filter(feature__is_digit=True)
    for pf in productfeatures:
        try:
            dimension = Dimension(feature=pf.feature, value=int(pf.value), unit=pf.unit, product=pf.product)
            dimension.save()
        except Exception as error:
            print(error)
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200223_2016'),
    ]

    operations = [
        migrations.RunPython(move_dimensions_from_product_features),
    ]
